"""Config for the UK stacked/segment forecasting engine.

Databricks pipeline requires .py (no .yaml/.json). This is the single source of truth
for UK; auto-generated from the former config_uk_base_local.yaml and loaded via
utils.config_loader.load_market_config("uk"). Edit CONFIG directly.
"""

CONFIG = {'target': 'actual_sales',
 'key_col': 'key',
 'time_col': 'year_week',
 'cat_col': 'category_name',
 'horizons': 13,
 'market_io': {'category_col': 'category_name',
               'cats_subdir': '01_all_keys_dr_adjusted',
               'fs_subdir': 'FS',
               'lego_pred_col': 'prediction_rf',
               'lego_subdir': 'TF_pristine_allkeys',   # FIX: was empty TF_modelling_pristine
               'ensemble_weights': 'config/uk_ensemble_weights.yaml',
               'segment_col': 'lego_segment'},          # ADD: routes UK to segment_engine (same as DE)
 'objective': 'tweedie',
 'tweedie_variance_power': 1.3,
 'num_leaves': 63,
 'learning_rate': 0.05,
 'n_estimators': 700,
 'min_data_in_leaf': 100,
 'lambda_l2': 1.0,
 'feature_fraction': 0.8,
 'bagging_fraction': 0.8,
 'bagging_freq': 1,
 'max_depth': -1,
 'recency_halflife_weeks': 39,
 'seed': 42,
 'num_threads': 0,
 'lags': [1, 2, 3, 4, 5, 6, 8, 13, 26, 52],
 'roll_windows': [4, 8, 13, 26],
 'extra_signal_cols': ['smooth_sales', 'nielsen_pos_sales_cases', 'retailer_pos_sales_cases'],
 'future_cov_prefixes': ['promo_',
                         'holiday_',
                         'season_',
                         'high_sunshine',
                         'low_sunshine',
                         'WTHR_',
                         'ice_ooh',
                         'pancake_',
                         'august_',
                         'weeks_to_'],
 'cat_features': ['category_name',
                  'segment_name',
                  'brand_name',
                  'APG_code',
                  'form_name',
                  'sub_sector_name'],
 'rich_features': False,
 'input_source': 'trim',
 'collapse_promo': False,
 'drop_promo_onehots': True,
 'holiday_distance_features': True,
 'seasonal_anchor': 'adaptive',
 'seasonal_lo': 0.5,
 'seasonal_hi': 2.0,
 'bias_calibration': True,
 'bias_calibration_holdout_weeks': 6,
 'bias_calibration_damp': 0.7,
 'calibrate_categories': ['DEODORANT & FRAGRANCE'],
 'bias_factor_min': 0.5,
 'bias_factor_max': 1.5,
 'per_category': False,
 'per_category_categories': None,
 'min_train_weeks': 8,
 'train_sample_frac': 1.0,
 'clip_negatives': True,
 'weight_fit': {'train_snapshots': ['2026-09', '2026-10', '2026-11', '2026-12', '2026-13', '2026-14'],
                'live_snapshot': '2026-23',
                'parent_dir_template': '/Volumes/pds_feu_931272_dev/eu_uk/landing/UK_PROD_NEW/lego_runs/forward_run/total_forecast/snapshot/{snapshot}',
                'panel_path_template': '/Volumes/pds_feu_931272_dev/eu_uk/landing/UK_PROD_NEW/lego_runs/forward_run/total_forecast/snapshot/{snapshot}/01_all_keys_dr_adjusted',
                'lego_path_template': '/Volumes/pds_feu_931272_dev/eu_uk/landing/UK_PROD_NEW/lego_runs/forward_run/total_forecast/snapshot/{snapshot}/TF_pristine_allkeys',
                'actuals_source': '/Volumes/pds_feu_931272_dev/eu_uk/landing/UK_PROD_NEW/lego_runs/forward_run/total_forecast/snapshot/2026-25/01_all_keys_dr_adjusted',
                'components_out_dir': '/Volumes/pds_feu_931272_dev/eu_uk/landing/UK_PROD_NEW/lego_runs/forward_run/_diq_fit/components',
                'live_parent_dir': '/Volumes/pds_feu_931272_dev/eu_uk/landing/UK_PROD_NEW/lego_runs/forward_run/total_forecast/snapshot/2026-23',
                'live_history_till': '202622',
                'horizons': 13,
                'grain': 'gtin',
                'objective': 'wape_asym',
                'bias_tolerance': 0.02,
                'guardrail': True,
                'guardrail_margin': 0.01,    # ADD: same robustness knob as DE
                'calibrate': False,          # ADD: E (calibrate-then-guardrail) available; off by default
                'in_scope_categories': ['BEVERAGE',
                                        'CONDIMENT',
                                        'COOKING AID',
                                        'DEODORANT & FRAGRANCE',
                                        'FABRIC CLEANING',
                                        'FABRIC ENHANCER',
                                        'HAIR CARE',
                                        'HEALTH & WELLBEING',
                                        'HOME & HYGIENE',
                                        'MINI MEAL',
                                        'ORAL CARE',
                                        'OTH FOOD',
                                        'SKIN CARE',
                                        'SKIN CLEANSING']}}
