"""Config for the DE stacked/segment forecasting engine.

Databricks pipeline requires .py (no .yaml/.json). This is the single source of truth
for DE; auto-generated from the former config_de_base_local.yaml and loaded via
utils.config_loader.load_market_config("de"). Edit CONFIG directly.
"""

CONFIG = {'target': 'Actuals',
 'key_col': 'key',
 'time_col': 'year_week',
 'cat_col': 'Category',
 'horizons': 13,
 'market_io': {'category_col': 'Category',
               'cats_subdir': 'DT',
               'fs_subdir': 'FS',
               'lego_pred_col': 'prediction_xgb',
               'lego_subdir': 'TF_pristine_allkeys',
               'ensemble_weights': 'config/de_ensemble_weights.yaml',
               'segment_col': 'lego_segment'},
 'objective': 'tweedie',
 'tweedie_variance_power': 1.3,
 'num_leaves': 63,
 'learning_rate': 0.05,
 'n_estimators': 700,
 'min_data_in_leaf': 100,
 'lambda_l2': 1.0,
 'feature_fraction': 0.8,
 'bagging_fraction': 0.8,
 'bagging_freq': 1,
 'max_depth': -1,
 'recency_halflife_weeks': 39,
 'seed': 42,
 'num_threads': 0,
 'lags': [1, 2, 3, 4, 5, 6, 8, 13, 26, 52],
 'roll_windows': [4, 8, 13, 26],
 'extra_signal_cols': ['SS_actual_sales', 'POS_actual_sales', 'smooth_sales', 'actual_dispatched_quantity'],
 'future_cov_prefixes': ['PromoMechanic_',
                         'PromoMechanic2_',
                         'PromoFeature_',
                         'PromoCommunication_',
                         'PromoFlag',
                         'Promo_Week',
                         'PromoStart',
                         'PromoSecond',
                         'Duration',
                         'holiday_',
                         'summer',
                         'winter',
                         'spring',
                         'autumn',
                         'high_sunshine',
                         'low_sunshine',
                         'month_end',
                         'month_start',
                         'quarter_start',
                         'quarter_end',
                         'f_'],
 'cat_features': ['Category', 'Brand', 'APG', 'Segment', 'ForecastFamilyDescription'],
 'rich_features': False,
 'input_source': 'dbx',
 'collapse_promo': False,
 'drop_promo_onehots': True,
 'holiday_distance_features': False,
 'seasonal_anchor': 'adaptive',
 'seasonal_lo': 0.5,
 'seasonal_hi': 2.0,
 'bias_calibration': False,
 'bias_calibration_holdout_weeks': 6,
 'bias_calibration_damp': 0.7,
 'calibrate_categories': [],
 'bias_factor_min': 0.5,
 'bias_factor_max': 1.5,
 'per_category': False,
 'per_category_categories': None,
 'min_train_weeks': 8,
 'train_sample_frac': 1.0,
 'clip_negatives': True,
 'weight_fit': {'train_snapshots': ['202601', '202606', '202611', '202616'],
                'live_snapshot': '202621',
                'parent_dir_template': '/Volumes/pds_feu_931272_dev/eu_dach/transform/DACH/DACH_LEGO/Germany/parallel_run/{snapshot}/All_Cat',
                'panel_path_template': '/Volumes/pds_feu_931272_dev/eu_dach/transform/DACH/DACH_LEGO/Germany/parallel_run/{snapshot}/All_Cat/DT',
                'lego_path_template': '/Volumes/pds_feu_931272_dev/eu_dach/transform/DACH/DACH_LEGO/Germany/parallel_run/{snapshot}/All_Cat/TF_pristine_allkeys',
                'actuals_source': '/Volumes/pds_feu_931272_dev/eu_dach/transform/DACH/DACH_LEGO/Germany/parallel_run/202625/All_Cat/DT',
                'components_out_dir': '/Volumes/pds_feu_931272_dev/eu_dach/transform/DACH/DACH_LEGO/Germany/parallel_run/_diq_fit/components',
                'live_parent_dir': '/Volumes/pds_feu_931272_dev/eu_dach/transform/DACH/DACH_LEGO/Germany/parallel_run/202621/All_Cat',
                'live_history_till': '202620',
                'horizons': 13,
                'grain': 'gtin',
                'objective': 'wape_asym',
                'bias_tolerance': 0.02,
                'guardrail': False,
                'guardrail_margin': 0.01,
                'calibrate': False,
                'in_scope_categories': ['SCRATCH COOKING AIDS',
                                        'DEODORANTS & FRAGRANCES',
                                        'DRESSINGS',
                                        'SKIN CLEANSING',
                                        'HEALTHY SNACKING',
                                        'HOME & HYGIENE',
                                        'FABRIC CLEANING',
                                        'ORAL CARE',
                                        'SKIN CARE',
                                        'HAIR CARE']}}
